name: academia_sport_mix
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.4.1
  flutter_svg: ^0.17.2
  http: ^0.12.0+4
  webview_flutter: ^0.3.19+8

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imagens/deadlift.png
    - imagens/foto_1.png
    - imagens/group.png
    - imagens/heart.png
    - imagens/followers.png
    - imagens/camera.png
    - imagens/academia.svg
    - imagens/exercite.svg
    - imagens/peso.svg
    - imagens/peso8.svg
    - imagens/core.svg
    - imagens/calendario.svg
    - imagens/juntos.svg
    - imagens/run.svg
